name: mwlr-standards

on: [push]

jobs         :
  build      :
    runs-on  : ubuntu-latest
    steps    :
      - name : 'Checkout'
        uses : 'actions/checkout@v2'
      - name : 'MWLR Standards'
        uses : manaakiwhenua/manaakiwhenua-standards@v0.1.1